### PR TITLE
Improving state validation and adding a new status at "STATE" global var "Grooming"

### PR DESCRIPTION
**Pull request by igorescobar**
Hi man!

Just a little corrections on your original cli to make it work with "grooming" status ;)

### CODE REVIEW

**Comment by oesmith** [comment]
LGTM! :+1:

**Comment by igorescobar** [comment]
Thanks!

**Comment by oesmith** [comment]
No worries!

BTW, feel free to open issues if ralio doesn't fit your process.. at the moment it's heavily skewed towards the way my team works (which is pretty unique, I think ;)).

**Comment by igorescobar** [comment]
Cool!
I discovered your Rally CLI a few seconds before start from scratch my own CLI, Lucky me!
If I found another problem I'll probably make a new pull request! ;)

When the new version will be available at NPM repository?

**Pull request merged**
