### PR TITLE
Updating version - Please deploy with new header changes

### PR DESCRIPTION
**Pull request by ferentchak**

### CODE REVIEW

**Comment by igorescobar** [comment]
That pull request isn't necessary. I'm going to release a new version (v0.6.1) very soon.

**Comment by ferentchak** [comment]
Cool, once you get that request shipped I will shoot you an email telling you how many people are using Ralio in a given month. I think it will he fun to learn!

**Comment by igorescobar** [comment]
Very nice!
It's already there! Sorry about the delay ;)

**Comment by igorescobar** [comment]
The big problem is that people aren't accustomed to upgrade npm packages very often so.. maybe a few months later :)

**Pull request closed without merging**
