### PR TITLE
Bug fixes and a little bit more :)

### PR DESCRIPTION
**Pull request by igorescobar**
The task._ref instruction throws an error when the typed task doesn't exist.
/usr/local/share/npm/lib/node_modules/ralio/lib/ralio.js:196
          _ref: task._ref,
                    ^
TypeError: Cannot read property '_ref' of undefined
    at Ralio.setTaskState (/usr/local/share/npm/lib/node_modules/ralio/lib/ralio.js:196:21)
    at Request.Ralio.bulk [as _callback](/usr/local/share/npm/lib/node_modules/ralio/lib/ralio.js:54:7)
    at Request.init.self.callback (/usr/local/share/npm/lib/node_modules/ralio/node_modules/request/main.js:120:22)
    at Request.EventEmitter.emit (events.js:99:17)
    at Request.<anonymous> (/usr/local/share/npm/lib/node_modules/ralio/node_modules/request/main.js:555:16)
    at Request.EventEmitter.emit (events.js:96:17)
    at IncomingMessage.Request.start.self.req.self.httpModule.request.buffer (/usr/local/share/npm/lib/node_modules/ralio/node_modules/request/main.js:517:14)
    at IncomingMessage.EventEmitter.emit (events.js:126:20)
    at IncomingMessage._emitEnd (http.js:366:10)
    at HTTPParser.parserOnMessageComplete [as onMessageComplete](http.js:149:23)

### CODE REVIEW

**Comment by igorescobar** [comment]
There is a little bit more of changes:
- A little bit more color to the task not found function
- better error handling is case of wrong config in .raliorc.
- making the sprint function works with the project or team config flag
- making the backlog function works with the project or team config flag

**Comment by oesmith** [comment]
:+1:

**Comment by oesmith** [comment]
... and I've just published v0.0.10 to npm, with these changes included!

**Comment by igorescobar** [comment]
Awesome! ;)

**Pull request merged**
