### PR TITLE
Discussion reading and commenting support

### PR DESCRIPTION
**Pull request by Two9A**
Introduces the `discuss` command, which can be used in one of two ways:

`ralio discuss DE123` will list the discussion posts on the artifact, in order;
`ralio discuss --add "Should be fixed." TA461` will add a comment onto the discussion, and list the new discussion in full.

### CODE REVIEW

**Comment by igorescobar** [comment]
There is anyway that we could delete and edit those discussion posts?

Would be nice if we could use it just like the ralio task command with the add and delete command and not --add and --delete.

**Comment by Two9A** [comment]
Discussion appears to be for quick notes against a ticket. As far as I can tell, discussion comments can't be edited or removed once they've been left; there's no interface in the Web UI for it, at least.

**Comment by igorescobar** [comment]
Cool, no problem.
What about the ralio discussion add instead of --add? Just to keep the same API as ralio task command.

Thanks for your contributions @Two9A really useful!

**Comment by igorescobar** [comment]
My mistake, the command is ralio task create instead of add.

**Comment by igorescobar** [comment]
@Two9A In that case, maybe is more appropriate to use "add" instead of "create".  Can you make the adjustment to the command work with add anstead of --add ?

**Comment by igorescobar** [comment]
What about loading discussions on the command ralio show? 
Do you think that would be nice? :+1: 
I could help you to implement that if you want :-)

**Comment by igorescobar** [comment]
Im going to merge this pullrequest and then we can discuss it in another episode :)

**Comment by igorescobar** [comment]
Thank you @Two9A , you rock! :+1:

**Comment by igorescobar** [comment]
I did small changes and a small bugfix on your pull-request but its all done in v0.6.0 of ralio, already available at npm repo.

**Comment by Two9A** [comment]
That's great, thanks. As for having discussions show up with `ralio show`, it's a good idea; perhaps as an additional switch.

Maybe the number of discussion comments could come through on `ralio sprint` as well? Things to think about...

**Comment by igorescobar** [comment]
I think we could do it on baby steps.
At the beginning we could only show the discussion thread on ralio show command, then we could start developing more features around the discussion feature and add more visibility of this data. As long as I can tell I never seen anybody using that "discussion" feature at Rally Web. Maybe we can keep that new ideas on hold and wait for an more concrete data of what the user really wants.

**Pull request merged**
