### PR TITLE
Allow the Rally host to be specified through a command line switch.

### PR DESCRIPTION
**Pull request by aesterline**
Not all users of rally use rally1.rallydev.com. I changed the code to allow the Rally host to be configured through a command line option.

I decided not to use a config file property, because most of the time people will want to use rally1.rallydev.com. But... at Rally we have tests systems that we sometimes want to access with ralio. A command line option seemed like the best choice.

### CODE REVIEW

**Comment by igorescobar** [comment]
Hi @aesterline 
(I'm glad to known that Ralio had been used by Rally's core development team :+1: )

This is how it works:
$ ralio --host http://rally.com/ 
And that host will take place on all ralio's commands executed after that instruction or I have to pass the -H option again on every further commands? (I did not tested it yet)

@oesmith thoughts?

**Comment by aesterline** [comment]
You have to pass -H on all future commands as well. I thought that if I was working on one of our development clusters, I would create an alias so that I wouldn't have to pass the -H on all calls.

$ alias rtest="ralio -H https://testcluster.rallydev.com"

I think it might be good in the future to expose all .raliorc options as command line options that way they can be mixed and matched.

**Comment by igorescobar** [comment]
Let see what @oesmith has in mind and then we're good to go ;)

**Comment by oesmith** [comment]
Yep, having command line flags to override options sounds like a very sensible idea to me.

:+1:

**Pull request merged**
